sparkmaster:
  image: birgerk/apache-spark
  ports:
  - 4040:4040
  - 7077:7077
  - 8080:8080
  environment:
   SPARK_ROLE: master

sparkslave:
  image: birgerk/apache-spark
  ports:
    - 8081:8081
  entrypoint: dockerize -wait tcp://sparkmaster:7077 -timeout 240s /sbin/my_init
  links:
    - sparkmaster
  environment:
    SPARK_MASTER: sparkmaster
    SPARK_ROLE: slave